# Generated by Django 5.2.1 on 2025-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0002_alter_curso_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
